// Copy for the pro studio (V6 "Rapport négocié") and the 3D scene labels,
// in the same languages as the public game (see src/game/i18n.js).

const n = (count, one, many) => (count > 1 ? many : one);

const fr = {
  views: { PACK: 'Boîte', EXPLODED: 'Ouverte', DIELINE: 'À plat', XRAY: 'Rayons X', PRESSURE: 'Charge' },
  slot: { LEFT_COPY: 'Gauche', FRONT: 'Avant', RIGHT_DATA: 'Droite', BACK: 'Dos' },
  surfaceThe: { FRONT: 'la face avant', LEFT_COPY: 'la gauche', RIGHT_DATA: 'la droite', BACK: 'le dos' },
  loud: { language: 'je veux la façade !', data: 'scannez-moi ICI', claim: 'moi d’abord.', warning: 'c’est obligatoire', eco: 'on me voit ?', barcode: 'je pousse…' },
  calm: { FRONT: 'la façade, merci', LEFT_COPY: 'gauche, ok', RIGHT_DATA: 'droite ✓', BACK: 'le dos, parfait' },
  marketNote: { EU: 'Traduction facultative ; les ingrédients sont au dos.', CANADA: 'Les mentions bilingues obligatoires occupent déjà la gauche.', US: 'Double unité de contenance devant ; un panneau « facts » plus lourd au dos.' },
  removeFromBrief: (name) => `Retirer ${name} du brief`,
  loading: 'Chargement du master Blender',
  masthead: 'Rapport de négociation · N° 19',
  editionsAria: 'Édition (marché)',
  edition: (m) => `Édition ${m}`,
  toolsAria: 'Outils',
  toGame: '← le jeu',
  skip: 'Passer',
  tour: 'Visite guidée',
  share: 'Partager',
  dieline: 'Dieline ⤓',
  soundOn: 'Son actif',
  soundOff: 'Son coupé',
  pageLeft: 'Page de gauche : le carton',
  chapterWord: 'CHAPITRE',
  fig1: 'FIG. 1 — LE CARTON',
  procedural: 'jumeau procédural',
  canvasAria: 'Carton 3D. Glisse une exigence sur une de ses faces.',
  viewsAria: 'Vues',
  unfold: 'DÉPLIER',
  unfoldAria: 'Déplier le carton',
  fig2: 'FIG. 2 — OÙ VIT CHAQUE EXIGENCE',
  loadCap: 'charge / capacité',
  toColumn: (count) => `→ la colonne de droite${count ? ` · ${count}` : ''}`,
  carton: 'CARTON',
  dimLetter: { width: 'L', depth: 'P', height: 'H' },
  dimAria: (key) => `Carton : ${{ width: 'largeur', depth: 'profondeur', height: 'hauteur' }[key]} en millimètres`,
  pageRight: 'Page de droite : la face avant',
  frontIsColumn: (w) => `FACE AVANT = CETTE COLONNE · ${w} MM`,
  faceEdge: 'BORD DE FACE',
  settled: (moves) => `ok — chacun sa face. ${moves ? `${moves} déplacé${moves > 1 ? 's' : ''}.` : ''} ✓`,
  stuck: 'même moi, je cale.',
  biggerCarton: (d) => `→ carton ${d.width} × ${d.depth} × ${d.height} mm ?`,
  removeOne: ' retire une exigence.',
  overfull: (faces, pct) => `${faces} : ${pct} % — trop plein.`,
  undo: 'Annuler',
  undoTitle: 'Annuler (Z)',
  sure: 'Sûr ?',
  restart: 'Recommencer',
  restartTitle: 'Recommencer (R)',
  compileTitle: 'Compiler (C)',
  editorDecides: 'l’éditeur tranche',
  wings: 'EN COULISSE',
  nobodyWaiting: 'personne — tout le monde est sur le carton',
  chapters: [['01', 'Le brief'], ['02', 'La mise en page'], ['03', 'La face avant'], ['04', 'L’éditeur'], ['05', 'La forme valide']],
  chaptersAria: 'Chapitres',
  truth: 'Concept · capacités de démonstration · ni réglementaire ni fabrication',
  editorNote: (step, total) => `NOTE DE L’ÉDITEUR · ${step} / ${total}`,
  skipEsc: 'passer · échap',
  toWings: 'en coulisse',
  noRoom: 'pas de place !',
  chapter: {
    running: ['04', 'L’éditeur', 'Le carton s’ouvre, se met à plat et se replie. Chaque exigence marche vers la face qui peut la porter.'],
    unsolved: ['04', 'L’impasse', 'Aucune répartition ne tient sur ce carton. Il faut retirer une exigence — ou agrandir le carton.'],
    collision: ['03', 'La face avant', 'La colonne de droite est la face avant. Elle déborde : la typographie se comprime et le dernier arrivé est éjecté.'],
    compiled: (m) => ['05', 'La forme valide', `Même master, nouvelle hiérarchie. Chacun a sa face — édition ${m}.`],
    empty: ['01', 'Le brief', 'Six exigences attendent en coulisse. Glisse-les sur le carton ou dans la colonne de droite.'],
    layout: ['02', 'La mise en page', 'Place les exigences. La colonne de droite est la face avant : elle a une limite.'],
  },
  headline: {
    running: 'L’ÉDITEUR REDISTRIBUE',
    unsolved: 'MÊME L’ÉDITEUR CALE',
    collision: 'LA FACE AVANT NE TIENT PLUS',
    compiled: 'CHACUN SA FACE',
    idle: 'LA FACE AVANT A UNE LIMITE',
  },
  say: {
    placed: (label, surface) => `${label} va sur ${surface}.`,
    added: (label) => `${label} entre en coulisse.`,
    undone: 'Dernier changement annulé.',
    valid: (m, moves) => `L'éditeur a tranché. Forme valide pour ${m}. ${moves} ${n(moves, 'exigence déplacée', 'exigences déplacées')}.`,
    invalid: 'Aucune mise en page ne tient sur ce carton.',
    edition: (m) => `Édition ${m}.`,
  },
  toast: {
    blank: 'Page blanche. Z pour revenir en arrière.',
    linkCopied: 'Lien copié — il rouvre exactement cette page.',
    copyLink: 'Copier ce lien',
    dieline: 'Dieline concept exportée · SVG · mm',
  },
  steps: [
    ['Un vrai carton Blender', 'À gauche, le master Blender : charnières, pot, capuchon, notice. À droite, la face avant — cette colonne.'],
    ['Tout le monde veut la façade', 'Les exigences sont des personnages. Chacun réclame la face avant.'],
    ['La colonne ne tient plus', 'La typographie se comprime, le dernier arrivé est éjecté dans la marge.'],
    ['L’éditeur tranche', 'Le carton s’ouvre, se met à plat, chaque exigence rejoint la face qui peut la porter.'],
    ['Même master, autre marché', 'Le Canada réserve la gauche aux mentions bilingues : l’éditeur trouve une autre répartition.'],
    ['Trois de plus en coulisse', 'Avertissements, allégation éco, code-barres. Cette fois, même l’éditeur cale.'],
  ],
  stepGrow: (mm, d) => [`+${mm} mm, et tout le monde tient`, `L’éditeur calcule le plus petit carton qui suffit : ${d.width} × ${d.depth} × ${d.height} mm.`],
  scene: {
    face: { FRONT: 'Avant', LEFT_COPY: 'Gauche', RIGHT_DATA: 'Droite', BACK: 'Dos' },
    load: (pct) => `${pct}% de charge`,
    over: 'trop plein !',
    fits: 'ça tient',
  },
};

const en = {
  views: { PACK: 'Box', EXPLODED: 'Open', DIELINE: 'Flat', XRAY: 'X-ray', PRESSURE: 'Load' },
  slot: { LEFT_COPY: 'Left', FRONT: 'Front', RIGHT_DATA: 'Right', BACK: 'Back' },
  surfaceThe: { FRONT: 'the front', LEFT_COPY: 'the left', RIGHT_DATA: 'the right', BACK: 'the back' },
  loud: { language: 'I want the front!', data: 'scan me HERE', claim: 'me first.', warning: 'I’m mandatory', eco: 'can you see me?', barcode: 'shove…' },
  calm: { FRONT: 'the front, thanks', LEFT_COPY: 'left, ok', RIGHT_DATA: 'right ✓', BACK: 'the back, perfect' },
  marketNote: { EU: 'Language copy is optional; ingredients sit on the back.', CANADA: 'Bilingual mandatory statements already occupy the left panel.', US: 'Dual-unit net quantity on the front; a heavier back facts panel.' },
  removeFromBrief: (name) => `Remove ${name} from the brief`,
  loading: 'Loading the Blender master',
  masthead: 'Negotiation report · No. 19',
  editionsAria: 'Edition (market)',
  edition: (m) => `${m} edition`,
  toolsAria: 'Tools',
  toGame: '← the game',
  skip: 'Skip',
  tour: 'Guided tour',
  share: 'Share',
  dieline: 'Dieline ⤓',
  soundOn: 'Sound on',
  soundOff: 'Sound off',
  pageLeft: 'Left page: the carton',
  chapterWord: 'CHAPTER',
  fig1: 'FIG. 1 — THE CARTON',
  procedural: 'procedural twin',
  canvasAria: '3D carton. Drag a requirement onto one of its sides.',
  viewsAria: 'Views',
  unfold: 'UNFOLD',
  unfoldAria: 'Unfold the carton',
  fig2: 'FIG. 2 — WHERE EACH REQUIREMENT LIVES',
  loadCap: 'load / capacity',
  toColumn: (count) => `→ the right-hand column${count ? ` · ${count}` : ''}`,
  carton: 'CARTON',
  dimLetter: { width: 'W', depth: 'D', height: 'H' },
  dimAria: (key) => `Carton ${key} in millimetres`,
  pageRight: 'Right page: the front panel',
  frontIsColumn: (w) => `FRONT PANEL = THIS COLUMN · ${w} MM`,
  faceEdge: 'PANEL EDGE',
  settled: (moves) => `ok — everyone has a side. ${moves ? `${moves} moved.` : ''} ✓`,
  stuck: 'even I’m stuck.',
  biggerCarton: (d) => `→ a ${d.width} × ${d.depth} × ${d.height} mm carton?`,
  removeOne: ' remove a requirement.',
  overfull: (faces, pct) => `${faces}: ${pct}% — overfull.`,
  undo: 'Undo',
  undoTitle: 'Undo (Z)',
  sure: 'Sure?',
  restart: 'Restart',
  restartTitle: 'Restart (R)',
  compileTitle: 'Compile (C)',
  editorDecides: 'the editor decides',
  wings: 'IN THE WINGS',
  nobodyWaiting: 'nobody — everyone is on the carton',
  chapters: [['01', 'The brief'], ['02', 'The layout'], ['03', 'The front'], ['04', 'The editor'], ['05', 'The valid form']],
  chaptersAria: 'Chapters',
  truth: 'Concept · demo capacities · not regulatory, not manufacturing',
  editorNote: (step, total) => `EDITOR’S NOTE · ${step} / ${total}`,
  skipEsc: 'skip · esc',
  toWings: 'to the wings',
  noRoom: 'no room!',
  chapter: {
    running: ['04', 'The editor', 'The carton opens, flattens and refolds. Each requirement walks to the side that can carry it.'],
    unsolved: ['04', 'Dead end', 'No layout fits this carton. Remove a requirement — or make the carton bigger.'],
    collision: ['03', 'The front', 'The right-hand column is the front panel. It overflows: the type squeezes and the last one in gets pushed out.'],
    compiled: (m) => ['05', 'The valid form', `Same master, new hierarchy. Everyone has a side — ${m} edition.`],
    empty: ['01', 'The brief', 'Six requirements wait in the wings. Drag them onto the carton or into the right-hand column.'],
    layout: ['02', 'The layout', 'Place the requirements. The right-hand column is the front panel: it has a limit.'],
  },
  headline: {
    running: 'THE EDITOR REDISTRIBUTES',
    unsolved: 'EVEN THE EDITOR IS STUCK',
    collision: 'THE FRONT CAN’T HOLD IT',
    compiled: 'EVERYONE HAS A SIDE',
    idle: 'THE FRONT HAS A LIMIT',
  },
  say: {
    placed: (label, surface) => `${label} goes on ${surface}.`,
    added: (label) => `${label} enters the wings.`,
    undone: 'Last change undone.',
    valid: (m, moves) => `The editor decided. Valid form for ${m}. ${moves} ${n(moves, 'requirement', 'requirements')} moved.`,
    invalid: 'No layout fits this carton.',
    edition: (m) => `${m} edition.`,
  },
  toast: {
    blank: 'Blank page. Z to go back.',
    linkCopied: 'Link copied — it reopens exactly this page.',
    copyLink: 'Copy this link',
    dieline: 'Concept dieline exported · SVG · mm',
  },
  steps: [
    ['A real Blender carton', 'Left: the Blender master — hinges, jar, cap, leaflet. Right: the front panel — this column.'],
    ['Everyone wants the front', 'Requirements are characters. Each one demands the front panel.'],
    ['The column can’t hold it', 'The type squeezes, and the last one in is pushed into the margin.'],
    ['The editor decides', 'The carton opens and flattens; each requirement goes to the side that can carry it.'],
    ['Same master, another market', 'Canada reserves the left side for bilingual text: the editor finds another layout.'],
    ['Three more in the wings', 'Warnings, eco claim, barcode. This time even the editor is stuck.'],
  ],
  stepGrow: (mm, d) => [`+${mm} mm, and everyone fits`, `The editor computes the smallest carton that works: ${d.width} × ${d.depth} × ${d.height} mm.`],
  scene: {
    face: { FRONT: 'Front', LEFT_COPY: 'Left', RIGHT_DATA: 'Right', BACK: 'Back' },
    load: (pct) => `${pct}% load`,
    over: 'overfull!',
    fits: 'fits',
  },
};

const es = {
  views: { PACK: 'Caja', EXPLODED: 'Abierta', DIELINE: 'Plana', XRAY: 'Rayos X', PRESSURE: 'Carga' },
  slot: { LEFT_COPY: 'Izquierda', FRONT: 'Delante', RIGHT_DATA: 'Derecha', BACK: 'Detrás' },
  surfaceThe: { FRONT: 'la cara delantera', LEFT_COPY: 'la izquierda', RIGHT_DATA: 'la derecha', BACK: 'la trasera' },
  loud: { language: '¡quiero la fachada!', data: 'escanéame AQUÍ', claim: 'yo primero.', warning: 'soy obligatorio', eco: '¿se me ve?', barcode: 'empujo…' },
  calm: { FRONT: 'la fachada, gracias', LEFT_COPY: 'izquierda, ok', RIGHT_DATA: 'derecha ✓', BACK: 'detrás, perfecto' },
  marketNote: { EU: 'La traducción es opcional; los ingredientes van detrás.', CANADA: 'Las menciones bilingües obligatorias ya ocupan la izquierda.', US: 'Doble unidad de contenido delante; una tabla «facts» más pesada detrás.' },
  removeFromBrief: (name) => `Quitar ${name} del briefing`,
  loading: 'Cargando el máster de Blender',
  masthead: 'Informe de negociación · N.º 19',
  editionsAria: 'Edición (mercado)',
  edition: (m) => `Edición ${m}`,
  toolsAria: 'Herramientas',
  toGame: '← el juego',
  skip: 'Saltar',
  tour: 'Visita guiada',
  share: 'Compartir',
  dieline: 'Troquel ⤓',
  soundOn: 'Sonido activado',
  soundOff: 'Sonido desactivado',
  pageLeft: 'Página izquierda: el cartón',
  chapterWord: 'CAPÍTULO',
  fig1: 'FIG. 1 — EL CARTÓN',
  procedural: 'gemelo procedural',
  canvasAria: 'Cartón 3D. Arrastra una exigencia a una de sus caras.',
  viewsAria: 'Vistas',
  unfold: 'DESPLEGAR',
  unfoldAria: 'Desplegar el cartón',
  fig2: 'FIG. 2 — DÓNDE VIVE CADA EXIGENCIA',
  loadCap: 'carga / capacidad',
  toColumn: (count) => `→ la columna derecha${count ? ` · ${count}` : ''}`,
  carton: 'CARTÓN',
  dimLetter: { width: 'A', depth: 'P', height: 'H' },
  dimAria: (key) => `Cartón: ${{ width: 'ancho', depth: 'profundidad', height: 'alto' }[key]} en milímetros`,
  pageRight: 'Página derecha: la cara delantera',
  frontIsColumn: (w) => `CARA DELANTERA = ESTA COLUMNA · ${w} MM`,
  faceEdge: 'BORDE DE CARA',
  settled: (moves) => `ok — cada uno su cara. ${moves ? `${moves} ${n(moves, 'movida', 'movidas')}.` : ''} ✓`,
  stuck: 'ni yo puedo.',
  biggerCarton: (d) => `→ ¿cartón de ${d.width} × ${d.depth} × ${d.height} mm?`,
  removeOne: ' quita una exigencia.',
  overfull: (faces, pct) => `${faces}: ${pct} % — desbordada.`,
  undo: 'Deshacer',
  undoTitle: 'Deshacer (Z)',
  sure: '¿Seguro?',
  restart: 'Reiniciar',
  restartTitle: 'Reiniciar (R)',
  compileTitle: 'Compilar (C)',
  editorDecides: 'el editor decide',
  wings: 'ENTRE BASTIDORES',
  nobodyWaiting: 'nadie — todos están en el cartón',
  chapters: [['01', 'El briefing'], ['02', 'La maqueta'], ['03', 'La cara delantera'], ['04', 'El editor'], ['05', 'La forma válida']],
  chaptersAria: 'Capítulos',
  truth: 'Concepto · capacidades de demostración · ni normativa ni fabricación',
  editorNote: (step, total) => `NOTA DEL EDITOR · ${step} / ${total}`,
  skipEsc: 'saltar · esc',
  toWings: 'entre bastidores',
  noRoom: '¡no hay sitio!',
  chapter: {
    running: ['04', 'El editor', 'El cartón se abre, se aplana y se vuelve a plegar. Cada exigencia camina hacia la cara que puede llevarla.'],
    unsolved: ['04', 'Callejón sin salida', 'Ninguna distribución cabe en este cartón. Hay que quitar una exigencia — o agrandar el cartón.'],
    collision: ['03', 'La cara delantera', 'La columna derecha es la cara delantera. Se desborda: la tipografía se comprime y el último en llegar sale expulsado.'],
    compiled: (m) => ['05', 'La forma válida', `Mismo máster, nueva jerarquía. Cada uno tiene su cara — edición ${m}.`],
    empty: ['01', 'El briefing', 'Seis exigencias esperan entre bastidores. Arrástralas al cartón o a la columna derecha.'],
    layout: ['02', 'La maqueta', 'Coloca las exigencias. La columna derecha es la cara delantera: tiene un límite.'],
  },
  headline: {
    running: 'EL EDITOR REDISTRIBUYE',
    unsolved: 'NI EL EDITOR PUEDE',
    collision: 'LA CARA DELANTERA NO DA MÁS',
    compiled: 'CADA UNO SU CARA',
    idle: 'LA CARA DELANTERA TIENE UN LÍMITE',
  },
  say: {
    placed: (label, surface) => `${label} va en ${surface}.`,
    added: (label) => `${label} entra entre bastidores.`,
    undone: 'Último cambio deshecho.',
    valid: (m, moves) => `El editor ha decidido. Forma válida para ${m}. ${moves} ${n(moves, 'exigencia movida', 'exigencias movidas')}.`,
    invalid: 'Ninguna maqueta cabe en este cartón.',
    edition: (m) => `Edición ${m}.`,
  },
  toast: {
    blank: 'Página en blanco. Z para volver atrás.',
    linkCopied: 'Enlace copiado — reabre exactamente esta página.',
    copyLink: 'Copia este enlace',
    dieline: 'Troquel conceptual exportado · SVG · mm',
  },
  steps: [
    ['Un cartón real de Blender', 'A la izquierda, el máster de Blender: bisagras, tarro, tapa, prospecto. A la derecha, la cara delantera — esta columna.'],
    ['Todos quieren la fachada', 'Las exigencias son personajes. Cada una reclama la cara delantera.'],
    ['La columna no da más', 'La tipografía se comprime y el último en llegar sale al margen.'],
    ['El editor decide', 'El cartón se abre y se aplana; cada exigencia va a la cara que puede llevarla.'],
    ['Mismo máster, otro mercado', 'Canadá reserva la izquierda a los textos bilingües: el editor encuentra otra distribución.'],
    ['Tres más entre bastidores', 'Advertencias, alegación eco, código de barras. Esta vez ni el editor puede.'],
  ],
  stepGrow: (mm, d) => [`+${mm} mm, y todos caben`, `El editor calcula el cartón más pequeño que basta: ${d.width} × ${d.depth} × ${d.height} mm.`],
  scene: {
    face: { FRONT: 'Delante', LEFT_COPY: 'Izquierda', RIGHT_DATA: 'Derecha', BACK: 'Detrás' },
    load: (pct) => `${pct} % de carga`,
    over: '¡desbordada!',
    fits: 'cabe',
  },
};

export const PRO = { fr, en, es };
